FROM liuchong/rustup:nightly

MAINTAINER Liu Chong <mail@clojure.cn>

WORKDIR /root

# musl tools
RUN apt-get update && \
    apt-get install --no-install-recommends -y \
    musl-tools && \
    rm -rf /var/lib/apt/lists/*

# all 3 musl targets
RUN rustup target add x86_64-unknown-linux-musl \
    --toolchain nightly-x86_64-unknown-linux-gnu

# make default target to musl
RUN mkdir /.cargo && \
    echo "[build]\ntarget = \"x86_64-unknown-linux-musl\"" > /.cargo/config
